//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportAtEnterprise.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.DriverCar = new HashSet<DriverCar>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> DateOfRelease { get; set; }
        public int Condition { get; set; }
        public int IDStatus { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CarStatus CarStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverCar> DriverCar { get; set; }
    }
}
