//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportAtEnterprise.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public int ID { get; set; }
        public int IDDriver { get; set; }
        public string Address { get; set; }
        public System.DateTime DateTo { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
